"""
Notifications Module — Service Layer

Creates, lists, and marks notifications as read.
Notifications are generated by the event bus (e.g. MSME alerts, EBS failures,
approval requests) and consumed by the frontend.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from backend.modules.notifications.models import Notification


# ---------------------------------------------------------------------------
# Create (called internally from event bus handlers)
# ---------------------------------------------------------------------------

async def create_notification(
    db: AsyncSession,
    notification_type: str,
    title: str,
    severity: str = "INFO",
    message: Optional[str] = None,
    link: Optional[str] = None,
    user_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a new notification."""
    notif = Notification(
        user_id=user_id,
        notification_type=notification_type,
        severity=severity,
        title=title,
        message=message,
        link=link,
    )
    db.add(notif)
    await db.commit()
    await db.refresh(notif)
    return _notif_to_dict(notif)


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------

async def list_notifications(
    db: AsyncSession,
    user_id: Optional[str] = None,
    unread_only: bool = False,
    limit: int = 50,
) -> List[Dict[str, Any]]:
    """List notifications, optionally filtered by user and read status."""
    q = select(Notification)
    if user_id:
        q = q.where(Notification.user_id == user_id)
    if unread_only:
        q = q.where(Notification.is_read == False)  # noqa: E712
    q = q.order_by(Notification.created_at.desc()).limit(limit)

    result = await db.execute(q)
    return [_notif_to_dict(n) for n in result.scalars().all()]


async def get_unread_count(
    db: AsyncSession,
    user_id: Optional[str] = None,
) -> int:
    """Count unread notifications."""
    q = select(func.count(Notification.id)).where(Notification.is_read == False)  # noqa: E712
    if user_id:
        q = q.where(Notification.user_id == user_id)
    result = await db.execute(q)
    return result.scalar() or 0


async def mark_read(
    db: AsyncSession,
    notification_id: str,
) -> Optional[Dict[str, Any]]:
    """Mark a single notification as read."""
    result = await db.execute(
        select(Notification).where(Notification.id == notification_id)
    )
    notif = result.scalar_one_or_none()
    if not notif:
        return None
    notif.is_read = True
    await db.commit()
    await db.refresh(notif)
    return _notif_to_dict(notif)


async def mark_all_read(
    db: AsyncSession,
    user_id: Optional[str] = None,
) -> int:
    """Mark all notifications as read. Returns count of updated rows."""
    q = update(Notification).where(Notification.is_read == False).values(is_read=True)  # noqa: E712
    if user_id:
        q = q.where(Notification.user_id == user_id)
    result = await db.execute(q)
    await db.commit()
    return result.rowcount


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _notif_to_dict(n: Notification) -> Dict[str, Any]:
    return {
        "id": n.id,
        "user_id": n.user_id,
        "notification_type": n.notification_type,
        "severity": n.severity,
        "title": n.title,
        "message": n.message,
        "link": n.link,
        "is_read": n.is_read,
        "created_at": n.created_at.isoformat() if n.created_at else None,
    }
